name: Server Library

on:
  workflow_dispatch:
  pull_request:
    paths:
      - package.json
      - libs/server/**
    branches:
      - main
  push:
    paths:
      - libs/server/**
    branches:
      - main

jobs:
  test:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: npm auth
        run: |
          npm config set @kashw2:registry https://npm.pkg.github.com/
          npm config set //npm.pkg.github.com/:_authToken=${{ secrets.GH_TOKEN }}
          npm config set registry https://registry.npmjs.org/

      - name: install globals
        run: npm install -g lerna

      - name: npm install
        run: npm ci --force

      - name: build libraries
        run: npm run build -w @kashw2/lib-util -w @kashw2/lib-external -w @kashw2/lib-ts

      - name: test server
        run: lerna run test --scope=@kashw2/lib-server
  build:
    if: github.event_name != 'push'
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: npm auth
        run: |
          npm config set @kashw2:registry https://npm.pkg.github.com/
          npm config set //npm.pkg.github.com/:_authToken=${{ secrets.GH_TOKEN }}
          npm config set registry https://registry.npmjs.org/

      - name: install globals
        run: npm install -g lerna rimraf typescript

      - name: npm install
        run: npm ci --force

      - name: build libraries
        run: npm run build -w @kashw2/lib-util -w @kashw2/lib-external -w @kashw2/lib-ts

      - name: build
        run: npm run build -w @kashw2/lib-util -w @kashw2/lib-ts
  publish:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: npm auth
        run: |
          npm config set @kashw2:registry https://npm.pkg.github.com/
          npm config set //npm.pkg.github.com/:_authToken=${{ secrets.GH_TOKEN }}
          npm config set registry https://registry.npmjs.org/

      - name: install globals
        run: npm install -g lerna rimraf typescript

      - name: npm install
        run: npm ci --force

      - name: build libraries
        run: npm run build -w @kashw2/lib-util -w @kashw2/lib-external -w @kashw2/lib-ts

      - name: build
        run: lerna run build --scope=@kashw2/lib-server

      - name: publish
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          package: ./libs/server/package.json
          registry: https://npm.pkg.github.com/
          strategy: all
